### ISSUE TITLE
Cloudformation for codepipeline release by cloudwatch events

### ISSUE THREAD

**Issue by LpmRaven** [awsdocs/amazon-cloudwatch-events-user-guide#13]
I found an [article](https://aws.amazon.com/about-aws/whats-new/2017/07/amazon-cloudwatch-events-now-supports-aws-codepipeline-as-a-target/) from 2017 saying that cloudwatch events now support codepipeline. How do I trigger a codepipeline once a day via cloudformation?

I thought it might look something like this, but I can't find any cloudformation examples regarding a scheduled trigger of a pipeline. I do also use webhooks to trigger my pipeline but I need to also run it once a day to update static pages with new data.
```
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !GetAtt Pipeline.Arn
          Id: id-here

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    ...
```
